services:
  mongodb:
    image: mongo:7.0
    container_name: mongo-transacciones-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: transacciones_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - ms4-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-transacciones:
    build: ./api
    image: br4yangc/cloud-bank-ms4:api-transacciones
    container_name: api-transacciones
    restart: on-failure
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@mongodb:27017/transacciones_db?authSource=admin
      SERVER_PORT: 8004
    ports:
      - "8004:8004"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - ms4-network

volumes:
  mongo_data:

networks:
  ms4-network:
    driver: bridge
